blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
	url(r'^post/new/$', views.post_new, name='post_new'),
	url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
	url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
	url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
	url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
]

gpower/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
	path('blog/', include('blog.urls', namespace='blog')),
	path('polls/', include('polls.urls', namespace='polls')),
	path('', TemplateView.as_view(template_name='index.html'), name="home"),
	path('about/', TemplateView.as_view(template_name='about.html'), name="about"),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='list'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text
		
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	
	def get_absolute_url(self):
		return u"/polls/%s/" % self.pk


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post
from .forms import PostForm

# Create your views here.
# FRONT END
def post_list(request):
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
	return render(request, 'blog/post_list.html', {'posts': posts})
	
def post_detail(request,pk):
	post = get_object_or_404(Post, pk=pk)
	return render(request, 'blog/post_detail.html', {'post': post})

# BACK END
@login_required
def post_draft_list(request):
	posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
	return render(request, 'blog/post_draft_list.html', {'posts': posts})

@login_required
def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			#post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = PostForm()
	return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			#post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = PostForm(instance=post)
	return render(request, 'blog/post_edit.html', {'form': form})

@login_required	
def post_publish(request,pk):
	post = get_object_or_404(Post, pk=pk)
	post.publish()
	return redirect('blog:post_detail', pk=pk)

@login_required	
def post_remove(request,pk):
	post = get_object_or_404(Post, pk=pk)
	post.delete()
	return redirect('blog:post_list')

polls/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import require_GET, require_POST
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseServerError
from django.template import loader
from .models import Question


# Create your views here.


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)
	
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	#return render(request, 'polls/results.html', {'question': question})
	return redirect(question.get_absolute_url())
	
@require_POST
def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	selected_choice = question.choice_set.get(pk=request.POST['selectionId'])
	selected_choice.votes += 1
	selected_choice.save()
	#return render(request, 'polls/results.html', {'question': question})
	return redirect('polls:results', question_id = question_id)

blog/templates/blog/base.html
{% extends "base.html" %}

{% block content %}

	{% block extra_css %}
		{% load static %}
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	{% endblock %}


<div class="page-header">
	{% if user.is_authenticated %}
	<a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
	<a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
	<p class="top-menu">Hello {{ user.username }} <small>(<a href="logout/">Log out</a>)</small></p>
	{% else %}
	<a href="login/" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
	{% endif %}
	<h1><a href="{% url 'blog:post_list' %}">Django Girls Blog</a></h1>
</div>
<div class="content container">
	<div class="row">
		<div class="col-md-8">
		{% block content_blog_app %}
		{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content_blog_app %}
		<nav class="editingtools">
			<a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
			<a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
			{% if not post.published_date %}<a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}"><span class="glyphicon glyphicon-upload"></a>{% endif %}
		</nav>
		{% if post.published_date %}<div class="date">published:{{ post.published_date }}</div>{% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
	{%if not posts%}
		<p>Non ci sono bozze</p>
	{% else %}
		{% for post in posts %}
			<div class="post">
				<p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
				<h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
				<p>{{ post.text|truncatechars:200 }}</p>
			</div>
		{% endfor %}
	{% endif %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content_blog_app %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content_blog_app %}
{% for post in posts %}
<div class="post">
	<div class="date">published: {{ post.published_date }}</div>
	<h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
	<p>{{ post.text|linebreaksbr }}</p>
</div>
{% endfor %}
{% endblock %}

polls/templates/polls/detail.html
{% extends "base.html" %}

{%block extra_js%}
<!-- JS libraries inclusion -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js" integrity="sha256-bu/BP02YMudBc96kI7yklc639Mu4iKGUNNcam8D2nLc=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/localization/methods_it.min.js" integrity="sha256-GTuWjmBsTdS9Y2jn6ucwOGGYQkpnFPHryPUPg3GrhJY=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-steps/1.1.0/jquery.steps.min.js" integrity="sha256-yUWanhHkxj+3ow0qZE6AtzP8lZkwLvPagULL6PnZMz0=" crossorigin="anonymous"></script>
<!-- JS custom -->
{% load staticfiles %}
<script type="text/javascript" src="{% static 'js/quizWizard.js' %}"></script>
{% endblock %}


{% block content %}
<!-- il blocco dei css sta dentro header.html che dipende da base. Per arrivarci devi passare dal blocco definito in base. -->
{% block extra_css %}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/leaf.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery-steps.css' %}" > 
{% endblock %}




<h1>{{ question.question_text }}</h1>
<form id="quiz-module" action="#">
 <input type="hidden" id="pollId" name="pollId" value="{{question.id}}">
{% csrf_token %}
	<div>
	<h3>Step</h3>
	<fieldset>
		<h2>{{ question.question_text }}</h2>
		<ul>
		{% for choice in question.choice_set.all %}
			<li><input type="radio" name="opt" value="{{ choice.id }}" {% if forloop.first %}required {%endif%}/>{{ choice.choice_text }}</li>
		{% endfor %}
		</ul>
	</fieldset>
	</div>
</form>
<section id="quiz-results">
	<h3>Il tuo voto</h3>
	<p id="ajaxresults"></p>
	<h3>Tutti i voti</h3>
	<dl>
		{%block updated_results %}{% endblock %}
	</dl>
</section>
<aside>
	<section>
		<h3>Info Box</h3>
		<dl>
			<dt>Category:<dt>
			<dd>Books</dd>
			<dt>Tags<dt>
			<dd>Fantasy, HP, Harry Potter</dd>
			<dt>Type:<dt>
			<dd>Knowledge quiz</dd>
			<dt>Creation date:<dt>
			<dd>12 dec 2018</dd>
			<dt>Author:<dt>
			<dd><a href="">Federica</a></dd> <!-- link to a dynamic page with all quizzes made by author (maybe) -->
			<dt>Visits<dt>
			<dd>5</dd>
		</dl>
	</section>
	<section>
		<h3>Related Contents</h3>
		<a href="">Harry Potter saga</a>
	</section>
</aside>
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}
{% block content %}

<article>
{% if latest_question_list %}
<div id="listing">
    {% for question in latest_question_list %}
		<article>
			{% load static %}
			<a href="{% url 'polls:detail' question.id %}"><img src="{% static 'assets/thumb.jpg' %}" alt="thumb"/></a>
			<h1><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></h1>
			<footer>
				<ul>
					<li>in <a href="">Book</a> - <a href="">Sci-fi</a></li>
					<li><a href="">Knowledge quiz</a></li>
					<li>1500 visits</li>
				</ul>
			</footer>
		</article>
    {% endfor %}
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}


{% endblock %}

polls/templates/polls/results.html
{%block updated_results %}
	{% for choice in question.choice_set.all %}
		<dt>{{ choice.choice_text }}:  </dt><dd id="choiceId-{{ choice.id }}">{{ choice.votes }}</dd>
	{% endfor %}
{% endblock %}

polls/templates/polls/vote.html
<!-- ajax is working for you --%>

templates/about.html
{% extends "base.html" %}

{% block content %}
<h1>Il gruppo di lavoro Girls Power</h1>
<h2>Un'iniziativa di CoderDojo Brianza con il sostegno di Micron Foundation</h2>

<p>Spiegone</p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
	{% include "header.html" %}
	<body>
		<div class="wrapper">
			{% include "menu.html" %}
			<header>
				<h1>Quiz lovers</h1>
				<h2>Test your fandomness, show your pride!</h2>
			</header>
			<main>
				{% block content %}
				{% endblock content %}
			</main>
			{% include "footer.html" %}
		</div>
		{%block extra_js%} {%endblock extra_js%}
	</body>
</html>

templates/footer.html
<footer>
	Copy note
</footer>

templates/header.html
{% load staticfiles %}
<head>
	<meta charset="utf-8">
	<title>GP - Quiz lovers</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{% block extra_css %}{% endblock %}
	<link href="https://fonts.googleapis.com/css?family=Londrina+Solid:300,400,900|Raleway:400,600,800" rel="stylesheet"> 
</head>

templates/index.html
{% extends "base.html" %}

{% block content %}
 ULTIMO POST
 ULTIMI n POLLS
{% endblock %}

templates/menu.html
<nav>
	<ul>
		<li><a href="{% url 'home' %}">Home</a></li>
		<li><a href="{% url 'about' %}">About</a></li>
		<li><a href="{% url 'polls:list' %}">Quiz</a></li>
		<li><a href="{% url 'blog:post_list' %}">Blog</a></li>
		<li><a href="#">Contact</a></li>
		<li><a href="#">My space</a></li>
	</ul>
</nav>